module LivreEnLigne {



    struct LivreChiffre {
	string contenu; 
	string cle;
    };
	
    struct InfoBancaires {
	string compte; 
	string code;
    };


    exception ExceptionMiseAJourLivre {
        string raison;
    };

    exception ExceptionNoLivreFound {
        string raison;
    };

    exception ExceptionEchecCommande {
        string raison;
    };

    exception ExceptionAuthorizationFailed {
        string raison;
    };

    exception ExceptionMoneyTransferRefused {
        string raison;
    };
	
    interface Lecteur {
        void miseAjourLivre(in string pAuteur, in string pTitre, in string pFournisseur) raises (ExceptionMiseAJourLivre);
        void confirmerTelechargement(in string pAuteur, in string pTitre, in string pFournisseur);
        void recevoirPret(in string pTitre, in string pAuteur, in string pContenu, in string pCle);
        void retirerPret(in string pTitre, in string pAuteur);
    };
	
    interface Fournisseur {
        float rechercherLivre(in string pTitre, in string pAuteur) raises (ExceptionNoLivreFound);
        void commander(in string pTitre, in string pAuteur, in string pCompte, in string pCode, in string pLecteur, in Lecteur pIorLecteur) raises (ExceptionEchecCommande);
        LivreChiffre telechargerLivre(in string pUtilisateur, in Lecteur IorUtulisateur, in string pTitre, in string pAuteur);
        void creerPret(in string pUtilisateurPreteur, in string pUtilisateurEmprunteur, in string pTitre, in string pAuteur);
        void retirerPret(in string pUtilisateurPreteur,in string pUtilisateurEmprunteur, in string pTitre, in string pAuteur);
    };
	

    struct InfoRecherche {
	string nomFournisseur;
	Fournisseur iorFournisseur;
	float prix;
    };

    interface Mandataire {
        InfoRecherche rechercherLivre(in string pTitre, in string pAuteur) raises (ExceptionNoLivreFound);
        void enregistrementFournisseur(in string pFournisseur,in Fournisseur pIorFournisseur);
    };
	
    interface Controleur {
        string verifierAutorisation(in string pAuteur, in string pTitre, in string pUtilisateur, in string pFournisseur) raises (ExceptionAuthorizationFailed);
        void enregistrerPret(in string pUtilisateurPreteur, in string pUtilisateurEmprunteur, in string pTitre, in string pAuteur, in string pFournisseur);
        void enregistrerAchat( in string pUtilisateur, in string pTitre, in string pAuteur, in string pFournisseur);
        void validerPret(in string pUtilisateurPreteur, in string pUtilisateurEmprunteur, in string pTitre, in string pAuteur, in string pFournisseur);
        void retirerPret(in string pUtilisateurPreteur, in string pUtilisateurEmprunteur, in string pFournisseur, in string pTitre, in string pAuteur);
    };

    interface Banque {
        void verifierCoordonneesBancaires(in string pCompte, in  string pCode) raises (ExceptionMoneyTransferRefused);
    };
};
